spring.application.name=ai-project-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_project_manager
spring.datasource.username=postgres
spring.datasource.password=opopop
openai.api.key=iuAzR07uf2f8AvVcaGpuJjAl2uBX6184Yd1kjL1C
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true