package com.yash.ai_project_manager.project.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yash.ai_project_manager.project.dto.*;
import com.yash.ai_project_manager.project.entity.Project;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class AIBootstrapService {

    private final ProjectService projectService;

    private final EpicService epicService;

    private final GroqService groqService;

    private final ObjectMapper objectMapper;

    public AIProjectCreationResponseDTO createProject(
            AIProjectCreationRequestDTO request
    ) {

        try {

            /*
             * Step 1
             * Create Project
             */
            ProjectRequestDTO projectRequest =
                    new ProjectRequestDTO(
                            request.name(),
                            request.requirement()
                    );

            Project project =
                    projectService.createProject(
                            projectRequest
                    );

            /*
             * Step 2
             * Generate Epics Using AI
             */
            String groqResponse =
                    groqService.generateEpics(
                            request.requirement()
                    );

            /*
             * Step 3
             * Parse Groq Response
             */
            JsonNode root =
                    objectMapper.readTree(
                            groqResponse
                    );

            String content =
                    root.path("choices")
                            .get(0)
                            .path("message")
                            .path("content")
                            .asText();

            /*
             * Remove markdown if AI returns:
             *
             * ```json
             * {
             * }
             * ```
             */
            content = content
                    .replace("```json", "")
                    .replace("```", "")
                    .trim();

            System.out.println(
                    "AI Response = " + content
            );

            /*
             * Step 4
             * Convert JSON String
             * to DTO
             */
            AIEpicResponseDTO response =
                    objectMapper.readValue(
                            content,
                            AIEpicResponseDTO.class
                    );

            /*
             * Step 5
             * Save Epics
             */
            for (String epicName : response.epics()) {

                EpicRequestDTO epicRequest =
                        new EpicRequestDTO(
                                epicName,
                                "Generated by AI",
                                project.getId()
                        );

                epicService.createEpic(
                        epicRequest
                );
            }

            /*
             * Step 6
             * Return Response
             */
            return new AIProjectCreationResponseDTO(
                    project.getId(),
                    project.getName(),
                    response.epics()
            );

        } catch (Exception e) {

            throw new RuntimeException(
                    "Failed to create AI project",
                    e
            );
        }
    }
}